baoiam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from core.views import maintenance_page, locked_page
from userauths import views
from dashboard import views
from course import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('userauths/', include('userauths.urls')),
    path('contactus/', include('contactapp.urls')),
    path('course/', include('course.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('maintenance/', maintenance_page, name='maintenance'),
    # path('locked/', locked_page, name='locked'),
    # path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('blog/', include('blog.urls', namespace='blog')),
    # For social auth

    path('auth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# blog/urls.py

from django.urls import path
from .views import category_list, post_list_by_category, post_detail

app_name = 'blog' 

urlpatterns = [
    path('categories/', category_list, name='categories'),
    path('category/<int:category_id>/', post_list_by_category, name='post_list_by_category'),
    path('post/<int:post_id>/', post_detail, name='post_detail'),
]

core/urls.py
from django.urls import path
# from course.views import categories
from core.views import index, career, hire_from_us, itie,wep, blog,pap, refer_earn, course, coming_soon, blog_details


app_name = 'core'

urlpatterns = [
    path("", index, name="index"),
    path("career/", career, name="career"),
    path("hire_from_us/", hire_from_us, name="hire_from_us"),
    path("itie/", itie, name="itie"),
    path("wep/", wep, name="wep"),
    path("blog/", blog, name="blog"),
    path("blog_details", blog_details, name="blog_details"),
    path("pap/", pap, name="pap"),
    path("refer_earn/", refer_earn, name="refer_earn"),
    path("coming_soon/", coming_soon, name="coming_soon"),
    path("course/", course, name="course"),
    # path('categories/', categories, name='categories'),
]

course/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from course import views


app_name = 'course'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('webdevelopment/',views.webdevelopment,name="webdevelopment"),
    # path('dataanalyst/',views.dataanalyst,name="dataanalyst"),
    # path('datascience/',views.datascience,name="datascience"),
    # path('contentwriting/',views.contentwriting,name="contentwriting"),
    # path('graphicdesigning/',views.graphicdesigning,name="graphicdesigning"),
    # path('seomarketing/',views.seomarketing,name="seomarketing"),
    # path('digitalmarketing/',views.digitalmarketing,name="digitalmarketing"),
    # path('projectmanagement/',views.projectmanagement,name="projectmanagement"),
    # path('humanresource/',views.humanresource,name="humanresource"),
    # path('corporatelaw/',views.corporatelaw,name="corporatelaw"),
    # path('enterpreneurship/',views.enterpreneurship,name="enterpreneurship"),
    # path('webdevelopment/',views.webdevelopment,name="webdevelopment"),
    
    # path('categories/', views.categories, name='categories'),
    path('categories/<int:category_id>/', views.category_courses, name='category_courses'),




]

dashboard/urls.py
from django.urls import path
from .views import user_ui, enroll_course, admin_ui


app_name = 'dashboard'

urlpatterns = [
    
    path('user_ui/', user_ui , name='user_ui'),
    path('admin_ui/', admin_ui , name='admin_ui'),
    path('enroll/<int:course_id>/', enroll_course, name='enroll_course'),
]

userauths/urls.py
from django.urls import path
from userauths.views import signup, login_view, logout_view, activate
from userauths.views import ResetPasswordView
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetCompleteView, CustomPasswordResetConfirmView

app_name = 'userauths'

urlpatterns = [
    path("signup/", signup, name='signup'),
    path("login/", login_view, name='login'),
    path("logout/", logout_view, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         CustomPasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

contactapp/models.py
from django.db import models

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.timestamp}"

blog/forms.py
# blog/forms.py

from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

dashboard/forms.py
from django import forms
from userauths.models import Dashboard_User

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = Dashboard_User
        fields = ['bio', 'fname', 'lname', 'mname', 'mobilenumber', 'photo', 'collegename', 'graduation_year', 'current_designation']
        

blog/views.py
# blog/views.py

from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Post, Comment
from .forms import CommentForm


def category_list(request):
    categories = Category.objects.all()
    print(categories)
    return render(request, 'blog.html', {'is_blog': True, 'categories': categories})

def post_list_by_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    posts = Post.objects.filter(category=category)
    categories=Category.objects.all()
    recent_posts = Post.objects.order_by('-pub_date')[:5]
    return render(request, 'posts.html', {'categories': categories,'category': category, 'posts': posts, 'is_blog_details':True, 'recent_posts': recent_posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post)
    user=request.user
    categories=Category.objects.all()
    recent_posts = Post.objects.order_by('-pub_date')[:5]

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return redirect('blog:post_detail', post_id=post_id)
    else:
        form = CommentForm()

    return render(request, 'post_detail.html', {'categories': categories,'post': post, 'comments': comments, 'form': form,'is_blog_details':True, 'user':user, 'recent_posts': recent_posts})

course/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from userauths.models import Dashboard_User
from .models import Course, CourseCategory
from django.db.models import Sum
from django.db import models
# import cv2
from django.shortcuts import render
from django.http import HttpResponse
from userauths.models import Dashboard_User

@login_required(login_url='/userauths/login/')
def category_courses(request, category_id):
    category = get_object_or_404(CourseCategory, id=category_id)
    courses = Course.objects.filter(category=category, status='active')
    categories = CourseCategory.objects.all()

    user = request.user
    if user.is_authenticated:
        dash_user, created = Dashboard_User.objects.get_or_create(user=user)
        enrolled_courses = dash_user.enrolled_courses.all()
        return render(request, 'course.html', {
            'is_category': True,
            'courses': courses,
            'enrolled_courses': enrolled_courses,
            'categories': categories
        })
    else:
        return render(request, 'course.html', {'is_course': True, 'courses': courses})

# def categories(request):
#     categories = CourseCategory.objects.all()
#     print(categories)
#     return render(request, 'test.html', {'categories': categories})
# @login_required(login_url='/userauths/login/')

# def webdevelopment(request):
#     web_dev_courses = Course.objects.filter(category='Web Development', status='active')
#     user = request.user
#     if user.is_authenticated:
#         dash_user, created = Dashboard_User.objects.get_or_create(user=user)
#         enrolled_courses = dash_user.enrolled_courses.all()
#         categories = CourseCategory.objects.all()
#         print(categories)
#         return render(request, 'webdevelopment.html', {
#             'is_webdevelopment_page': True,
#             'web_dev_courses': web_dev_courses,
#             'enrolled_courses': enrolled_courses,
#             'categories':categories
#         })
#     else:
#         return render(request, 'webdevelopment.html', {
#             'is_webdevelopment_page': True,
#             'web_dev_courses': web_dev_courses
#         })
# def dataanalyst(request):
#     data_analyst_courses = Course.objects.filter(category='Data Analyst', status='active')
#     return render(request, 'dataanalyst.html', {'is_dataanalyst_page': True, 'data_analyst': data_analyst_courses})

# def datascience(request):
#     data_science_courses = Course.objects.filter(category='Data Science', status='active')
#     return render(request, 'datascience.html', {'is_datascience_page': True, 'data_science_courses': data_science_courses})


# def contentwriting(request):
#     content_Writing_courses = Course.objects.filter(category='content Writing', status='active')
#     return render(request, 'contentwriting.html', {'is_contentWriting_page': True, 'content_Writing': content_Writing_courses})

# def graphicdesigning(request):
#     graphic_designing_courses = Course.objects.filter(category='Graphic Designing', status='active')
#     return render(request, 'graphicdesigning.html', {'is_graphicdesigning_page': True, 'graphic_designing': graphic_designing_courses})

# def seomarketing(request):
#     seo_marketing_courses = Course.objects.filter(category='SEO Marketing', status='active')
#     return render(request, 'seomarketing.html', {'is_seomarketing_page': True, 'seo_marketing': seo_marketing_courses})


# def digitalmarketing(request):
#     digital_marketing_courses = Course.objects.filter(category='Digital Marketing', status='active')
#     return render(request, 'digitalmarketing.html', {'is_digitalmarketing_page': True, 'digital_marketing': digital_marketing_courses})

# def projectmanagement(request):
#     project_management_courses = Course.objects.filter(category='Project Management', status='active')
#     return render(request, 'projectmanagement.html', {'is_projectmanagement_page': True, 'projectmanagement': project_management_courses})

# def humanresource(request):
#     human_resource_courses = Course.objects.filter(category='Human Resource', status='active')
#     return render(request, 'humanresource.html', {'is_humanresource_page': True, 'human_resource': human_resource_courses})

# def corporatelaw(request):
#     corporate_law_courses = Course.objects.filter(category='Corporate  Law', status='active')
#     return render(request, 'corporatelaw.html', {'is_corporatelaw_page': True, 'corporate_law': corporate_law_courses})

# def enterpreneurship(request):
#     enterpreneurship_courses = Course.objects.filter(category='Enterpreneurship', status='active')
#     return render(request, 'enterpreneurship.html', {'is_enterpreneurship_page': True, 'enterpreneurship': enterpreneurship_courses})


##

#def watch_video(request, course_id):
    # Assuming you have a Course model with a video_name field
    # course = Course.objects.get(id=course_id)
    # video_path = "{Course.video_name}"

    # cap = cv2.VideoCapture(video_path)
    # start_time = cv2.getTickCount()

    # while cap.isOpened():
    #     ret, frame = cap.read()

    #     if not ret:
    #         break  # Break the loop if there are no more frames to read

    #     cv2.imshow("Video", frame)

    #     if cv2.waitKey(30) & 0xFF == 27:  # Press 'Esc' to exit
    #         break

    # end_time = cv2.getTickCount()
    # elapsed_time = (end_time - start_time) / cv2.getTickFrequency()

    #  # Save the elapsed_time in the watchedTime field of the DashboardUser model
    # dashboard_user, created = Dashboard_User.objects.get_or_create(user=request.user)
    # dashboard_user.watchedTime += elapsed_time
    # dashboard_user.save()

    # # Here, you can save the elapsed_time in your database or perform other actions
    # # For simplicity, let's just print the time
    # print(f"User watched the video for {elapsed_time:.2f} seconds")

    # cap.release()
    # cv2.destroyAllWindows()

    # return HttpResponse("Video watched successfully!")





#def user_progress(request,course_id):
 #   course = get_object_or_404(Course,pk=course.id)
    #current user logged in
  #  user = request.user
   # videos = course.videos.all()
    #total_duration = sum(video.duration for video in videos)
    #course.duration_field = total_duration
    #Course.save()
    #watched_duration = Course.objects.filter(user=user, video__in=videos).aggregate(models.Sum('watched_duration'))['watched_duration__sum']
    #progress_percentage = (watched_duration / total_duration) * 100 if total_duration > 0 else 0
    #context = {
     #   'course': course,
      #  'progress_percentage': progress_percentage,
    #}

    
    #return render(request,'dashboard.html', context)

dashboard/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render, redirect
from course.models import Course
from .forms import UserUpdateForm
from userauths.models import Dashboard_User
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction

@login_required(login_url="/userauths/login/")
@transaction.atomic
def user_ui(request):
    if request.method == "GET":
        auser = request.user
        if request.user.is_authenticated:
            if auser.is_staff == True:
                return redirect("/admin")
            else:
                # username = request.session['username']
                user = User.objects.get(username=request.user.username)
                if not Dashboard_User.objects.filter(user_id=user.id).exists():
                    dashboard_user, created = Dashboard_User.objects.get_or_create(user=auser)
                    dashboard_user.save()
                dash_user = Dashboard_User.objects.get(user_id=user.id)
                # all_courses = Course.objects.all()
                enrolled_courses = dash_user.enrolled_courses.filter(status="active")
                return render(
                    request,
                    "dashboard.html",
                    {
                        "user": user,
                        "dash_user": dash_user,
                        "enrolled_courses": enrolled_courses,
                    },
                )
        else:
            return redirect("userauths:login")
    if request.method == "POST":
        user_profile = Dashboard_User.objects.get(user=request.user)

    if request.method == "POST":
      #get from frontend
        first_name = request.POST.get("first_name")
        middle_name = request.POST.get("middle_name")
        last_name = request.POST.get("last_name")
        mobile_number = request.POST.get("mobile_number")
        college_name = request.POST.get("college_name")
        graduation_year = request.POST.get("graduation_year")
        bio = request.POST.get("mobile_number")
        # Update user details
        user_profile.fname = first_name
        user_profile.mname = middle_name
        user_profile.lname = last_name
        user_profile.mobilenumber = mobile_number
        user_profile.collegename = college_name
        user_profile.graduation_year = graduation_year
        user_profile.bio = bio
        # Save changes
        user_profile.save()
        # messages.success(request, "Profile updated successfully")
        return redirect("dashboard:user_ui")
    return render(request, "dashboard.html", {"user": request.user})


def admin_ui(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            auser = request.user
            if auser.is_staff == True:
                return redirect("core:index")
            else:
                return redirect("/admin")
        else:
            return redirect("core:index")


@login_required(login_url="/userauths/login/")
def enroll_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    dashboard_user, created = Dashboard_User.objects.get_or_create(user=request.user)
    dashboard_user.enrolled_courses.add(course)
    # messages.success(request, f"You have successfully enrolled in {course.title}.")
    return redirect("dashboard:user_ui")

templates/coming_soon.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'comingsoon/css/style.css' %}">
  <title>Coming Soon</title>
</head>
<body>
  <div class="container">
    <div class="image">
      <img src="{% static 'comingsoon/img/Coming_Soon_Baoiam.png' %}" alt="Comming soon image">
    </div>
    <div class="text">
      <h4>Stay Connected, <span class="underline">Stay Updated!</span></h4>
      <button><a href="{% url 'core:index' %}">Go to Home</a></button>
    </div>
  </div>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'authentication/css/style1.css' %}">
  <title>Login-Page</title>

   <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script>
    // Display Django messages including form errors using SweetAlert2
    {% if messages %}
        document.addEventListener('DOMContentLoaded', function() {
            {% for message in messages %}
                {% if message.tags == "error" %}
                    Swal.fire({
                        icon: 'error',
                        title: "{{ message|escapejs }}",
                        showConfirmButton: true, // Display a close button for errors
                    });
                {% else %}
                    Swal.fire({
                        icon: '{% if message.tags == "success" %}success{% elif message.tags == "warning" %}warning{% else %}info{% endif %}',
                        title: "{{ message|escapejs }}",
                        showConfirmButton: false,
                        timer: 5000
                    });
                {% endif %}
            {% endfor %}
        });
    {% endif %}
</script>



</head>

<body>

  <div class="cir"></div>
  <div class="cir2"></div>

  <div class="main">
    <div class="box1">
      <div class="container">
        <div class="Bimg">
          <img src="{% static 'authentication/img/brand.png' %}" alt="" style="width: 150px;">
        </div>
        <h1>Sign In</h1>
        <form method="POST">
          {% csrf_token %}

          <div class="username">
            <div class="icon"><i class="fas fa-user"></i></div>
            <div class="inputbox"><input type="username" name="username" class="" placeholder="username"></div>
          </div>

          <div class="password">
            <div class="icon"><i class="fas fa-lock"></i></div>
            <div class="inputbox">

              <input type="password" name="password" class="" placeholder="Password">
            </div>
          </div>
          <div class="forgot">
            <a href="{% url 'userauths:password_reset' %}">Forgot Password</a>
          </div>
          <div>
            <div class="inbtn">

            <button class="subbtn" type="submit">Sign In</button>
            <p class="pin" style="padding: 0 10px;">Or</p>
            <div  class="signinBtnpin">
              <a style="color: white;" href="{% url 'userauths:signup' %}">Sign Up</a>
            </div>
          </div>

          </div>
        </form>
        <div class="social">
          <p class="socialP">Or Sign up with social platforms</p>
          <div class="icons">
              <div class="circle"><a href="{% url 'social:begin' 'github' %}"><i class="fab fa-github fa-2x"></i></a></div>
              <div class="circle"><a href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fab fa-google"></i></a></div>

          </div>
        </div>
      </div>
    </div>
    <div class="box2">
      <div class="oneAndSign">
        <div class="oneOfUs">
          <h2>New here?</h2>
          <p>Those who see possibilities where other see limitations deserve to Be one in A Million!</p>
        </div>
        <div class="signinBtn">
          <a href="{% url 'userauths:signup' %}">Sign Up</a>
        </div>
      </div>
      <div class="image">
              <img src="{% static 'authentication/img/log.svg' %}" class="img" alt="">
      </div>
    </div>
  </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js" integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'authentication/js/login.js' %}"></script>
</html>

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-4 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-warning">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="#">Create A New Account</a><br><br>
                                <a href="#">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

templates/post_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- blog/templates/blog/post_detail.html -->

<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog - {{ post.title }}</title>
</head>
<body>
    <header>
        <h1><a href="{% url 'blog:categories' %}">My Blog</a></h1>
    </header>
    <main>
        <h1>{{ post.title }}</h1>
        <p>{{ post.content|linebreaks }}</p>
        <p>Created by: {{ post.created_by.username }}</p>

        <h2>Comments</h2>
        {% for comment in comments %}
            <p>{{ comment.user.username }} on {{ comment.created_at }}:</p>
            <p>{{ comment.text }}</p>
        {% endfor %}

        <h3>Add a comment</h3>
        <form method="post" action="{% url 'blog:post_detail' post_id=post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </main>
</body>
</html>-->



<section>
  <div class="main-blog">
    <div class="blog-left">
      <div class="blog-left1">
        <img src="../images/blog1.jpg" alt="" />

        <div class="blog-left-icon">
          <span><i class="fa fa-regular fa-user" aria-hidden="true"> </i>By
            {{post.created_by.username}}</span>
          
          <br />
          <br />
          
        </div>

        <div class="blog-content">
          <h2>{{post.title}}</h2>
          <br>
          
          <p>{{ post.content|linebreaks }}</p>

        </div>




        <!-- Social Icons -->

        <!--<div class="social-icons">

          <div class="tags">
            <div class="tag-name">Tags:</div>
            <div class="education">Education </div>
            <div class="online">Online</div>
          </div>
          <div class="share-icon">

            <span class="icon">
              <div class="heading">Share:</div>

              <div class="sub-icon">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
              </div>
            </span>
          </div>

        </div>

      </div>-->


      <!-- Comment Section -->
      <!-- <section> -->
        
        <div class="blog-left2">
            <h2>Comments</h2>
            <div class="comments-section">
                {% for comment in comments %}
                    <div class="comment">
                        <p>{{ comment.text }}</p>
                        <div class="comment-meta">
                            <i class="fa fa-regular fa-user" aria-hidden="true"></i> By {{ comment.user.username }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        
            {% if user.username %}
                <div class="comment-form-section">
                    <h3>Add a Comment</h3>
                    <form method="post" action="{% url 'blog:post_detail' post_id=post.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Submit</button>
                    </form>
                </div>
            
            {% endif %}
        </div>
        



    <!-- </div> -->


    <!-- Right section -->
    <div class="blog-right">
        <div class="main-search">
          <div class="search">
            <input type="text" name="search" id="search" placeholder=" Search .." />
            <li class="fas fa-search"></li>
          </div>
        </div>
  
        <div class="categoery">
          <h3>Categories</h3>
  
          {% for category in categories %}
          <a href="{% url 'blog:post_list_by_category' category.id %}" class="course_btn" >
            <div class="categoery1">
              <span><i class="fa fa-play"></i>{{category.name}}</span>
            </div>
          </a>
  
            {% endfor %}
            
          </div>
  
  
          
  
        <div class="posts">
          <h3>Recent Posts</h3>
  
          {% for post in recent_posts %}
          <div class="post1">
            <!--<img src="../images/blog2.jpg" alt="" />-->
            <div class="post-content">
              <h4><a href="{% url 'blog:post_detail' post_id=post.id %}">
                  {{post.title}}</a>
              </h4>
              <span><i class="fa fa-calendar" aria-hidden="true"> </i>{{post.pub_date}}</span>
            </div>
  
            {% endfor%}
          </div>
  
          
  
  
        </div>
      </div>
</section>

{% endblock content %}